Upgrade to Helm Chart 3
ergon/airlock-helm-charts pull request #163
Opened 2022-06-20 10:20 UTC by orltom

## Description
Upgrade Microgateway Chart to Helm Chart 3 and update dependencies.

## Hints
- Bitnami Redis Helm Chart Values need to be migrated. For more information see https://github.com/bitnami/charts/tree/master/bitnami/redis#upgrading
- Run unit tests with Helm3

2022-06-20 13:39 UTC, orltom commented on charts/microgateway/values.yaml
> -  securityContext:
Please review the following changes carefully. With the Bitnami Redis chart upgrade, the default Redis parameters need to be mapped to new parameters from the Redis Helm Chart. For more information see: https://github.com/bitnami/charts/tree/master/bitnami/redis#upgrading

2022-06-20 13:41 UTC, orltom commented on charts/microgateway/Chart.yaml
> +dependencies:
With Helm3 the dependencies need to be declared in Chart.yaml

2022-06-20 13:44 UTC, orltom commented on charts/microgateway/tests/__snapshot__/configmap_test.yaml.snap
> -dsl example:
Unclear why this file is required.

2022-06-20 14:17 UTC, libuweber commented on charts/microgateway/.gitignore
> +tests/__snapshot__/
This folder and the files contained within are used in the unit test configmap_test.yaml as a reference for correct output. They should not be deleted.
The DEVELOPER_NOTES.md contains information on using / updating the snapshots.

2022-06-21 06:43 UTC, libuweber commented on charts/microgateway/Chart.yaml
> +  - name: redis
The dependency seems to produce a warning during installation: coalesce.go:203: warning: destination for repository is a table. Ignoring non-table value bitnami/redis

2022-06-21 06:45 UTC, libuweber requested changes
please fix the config map unit test

2022-06-21 08:20 UTC, orltom commented on charts/microgateway/.gitignore
> +tests/__snapshot__/
Thank you for your clarification

2022-06-21 08:32 UTC, orltom commented on charts/microgateway/Chart.yaml
> +  - name: redis
Unclear how to fix or ignore this warning message. Any hints are welcome :)

2022-06-21 08:57 UTC, libuweber approved these changes

2022-06-21 09:00 UTC, merged